name: Trigger auto deployment for queuereader

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'queuereaderapp/**'
    - '.github/workflows/queuereader-AutoDeployTrigger-1941f55b-9a9a-4b73-beff-9b58d4759950.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: chrilleguvenacr.azurecr.io
          username: ${{ secrets.QUEUEREADER_REGISTRY_USERNAME }}
          password: ${{ secrets.QUEUEREADER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: chrilleguvenacr.azurecr.io/queuereader:${{ github.sha }}
          file: ./queuereaderapp/Dockerfile
          context: ./queuereaderapp/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.QUEUEREADER_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n queuereader -g chrilleguven-rg --server chrilleguvenacr.azurecr.io --username  ${{ secrets.QUEUEREADER_REGISTRY_USERNAME }} --password ${{ secrets.QUEUEREADER_REGISTRY_PASSWORD }}
            az containerapp update -n queuereader -g chrilleguven-rg --image chrilleguvenacr.azurecr.io/queuereader:${{ github.sha }}
